version: "3.9"
services:
    test:
      image: "exercise-9"
      volumes:
        - ./data:/app/data
        - ./main.py:/app/main.py
      command: python3.8 -m pytest
    run:
      image: "exercise-9"
      volumes:
        - ./data:/app/data
        - ./main.py:/app/main.py
      command: python3.8 main.py